#pragma once

#include <cstdint>
#include <stdexcept>
#include <string>
#include <vector>

/**
 * @class ProvablyFairCore
 * @brief Core engine for cryptographic and deterministic game calculations.
 *
 * This class isolates the game logic to ensure that random outcomes
 * cannot be manipulated by the Android client or memory editors.
 * It uses the Provably Fair model (HMAC-SHA256) to guarantee transparency.
 */
class ProvablyFairCore
{
public:
  /**
   * @brief Calculates a fair coinflip result based on server and client seeds.
   *
   * @param serverSeed  Immutable cryptographic string generated by the server.
   * @param clientSeed  User-provided string adding external entropy.
   * @param nonce       Incremental round counter preventing replay attacks.
   * @return std::string The resulting bit ("0" or "1") followed by a pipe '|'
   * and the hash.
   */
  static std::string calculateCoinflip(const std::string &serverSeed,
                                       const std::string &clientSeed,
                                       long nonce);

  /**
   * @brief Calculates a fair European Roulette outcome (0-36).
   *
   * Incorporates rejection sampling to mathematical perfection, preventing
   * modulo bias when isolating the winning pocket.
   *
   * @param serverSeed Immutable cryptographic string generated by the server.
   * @param clientSeed User-provided string adding external entropy.
   * @param nonce      Incremental round counter preventing replay attacks.
   * @return std::string The winning number (0-36) followed by a pipe '|' and
   * the hash.
   */
  static std::string calculateRoulette(const std::string &serverSeed,
                                       const std::string &clientSeed,
                                       long nonce);

  /**
   * @brief Calculates a fair Crash game multiplier.
   *
   * Uses 52 bits of the hash to create a uniform float, then maps it to an
   * exponential curve with a house edge.
   *
   * @param serverSeed Immutable cryptographic string generated by the server.
   * @param clientSeed User-provided string adding external entropy.
   * @param nonce      Incremental round counter preventing replay attacks.
   * @return std::string The crash point (float string) followed by '|' and
   * hash.
   */
  static std::string calculateCrashPoint(const std::string &serverSeed,
                                         const std::string &clientSeed,
                                         long nonce);

  /**
   * @brief Calculates a series of mine locations (0-24) without repetitions.
   *
   * Uses Rejection Sampling and limited Fisher-Yates array shuffling logic.
   *
   * @param serverSeed Immutable cryptographic string generated by the server.
   * @param clientSeed User-provided string adding external entropy.
   * @param nonce      Incremental round counter preventing replay attacks.
   * @param numMines   The number of mines to place on the board (1 to 24).
   * @return std::string Comma-separated mine positions followed by '|' and
   * hash.
   */
  static std::string calculateMines(const std::string &serverSeed,
                                    const std::string &clientSeed, long nonce,
                                    int numMines);

  /**
   * @brief Calculates the permutation of a 52-card standard deck.
   *
   * @note To avoid memory leaks and JNI state coupling, the core engine
   * calculates and returns the fully shuffled deck array upfront.
   * Kotlin manages the state (dealing sequence) iteratively.
   *
   * @param serverSeed Immutable cryptographic string generated by the server.
   * @param clientSeed User-provided string adding external entropy.
   * @param nonce      Incremental round counter preventing replay attacks.
   * @return std::string Comma-separated 52 cards followed by '|' and hash.
   */
  static std::string calculateBlackjackDeck(const std::string &serverSeed,
                                            const std::string &clientSeed,
                                            long nonce);

private:
  // --- Constants ---
  static constexpr int ROULETTE_OUTCOMES = 37;
  static constexpr int MINES_GRID_SIZE = 25;
  static constexpr int MIN_MINES = 1;
  static constexpr int MAX_MINES = MINES_GRID_SIZE - 1; // 24
  static constexpr int BLACKJACK_DECK_SIZE = 52;
  static constexpr int CRASH_HASH_HEX_DIGITS = 13;
  static constexpr double CRASH_ENTROPY_SPACE = 4503599627370496.0; // 2^52
  static constexpr uint32_t MAX_UINT32 = 4294967295U;
  static constexpr int HEX_CHARS_PER_32BIT_BLOCK = 8;
  static constexpr int ROULETTE_BLOCK_HEX_CHARS = 4;
  static constexpr int REJECTION_SAFETY_LIMIT = 100;

  /**
   * @brief Generates an HMAC-SHA256 signature and returns its hexadecimal
   * string.
   *
   * @note Uses a direct char lookup table instead of std::stringstream for
   * hex formatting, eliminating the <sstream> dependency from the core engine.
   *
   * @param key The secret key (Server Seed).
   * @param msg The message to sign (Client Seed + ":" + Nonce).
   * @return std::string A 64-character lowercase hex string.
   */
  static std::string generateHMAC_SHA256(const std::string &key,
                                         const std::string &msg);

  /**
   * @brief Builds the standard HMAC message from client seed and nonce.
   *
   * Centralizes the "clientSeed:nonce" concatenation pattern used by every
   * game algorithm.
   *
   * @param clientSeed User-provided seed string.
   * @param nonce      Round counter.
   * @return std::string Formatted as "clientSeed:nonce".
   */
  static std::string buildMessage(const std::string &clientSeed, long nonce);

  /**
   * @brief Parses a hexadecimal substring into a 32-bit unsigned integer.
   *
   * @param hex    Full hex string to read from.
   * @param offset Starting character position.
   * @param len    Number of hex characters to parse.
   * @return uint32_t The parsed unsigned value.
   */
  static uint32_t parseHex32(const std::string &hex, size_t offset, size_t len);

  /**
   * @brief Parses a hexadecimal substring into a 64-bit unsigned integer.
   *
   * @param hex    Full hex string to read from.
   * @param offset Starting character position.
   * @param len    Number of hex characters to parse.
   * @return uint64_t The parsed unsigned value.
   */
  static uint64_t parseHex64(const std::string &hex, size_t offset, size_t len);

  /**
   * @brief Joins a vector of integers into a comma-separated string.
   *
   * @param values The integers to serialize.
   * @return std::string Comma-delimited representation (e.g. "1,20,14,9,23").
   */
  static std::string joinCsv(const std::vector<int> &values);

  /**
   * @brief Performs unbiased random selection via rejection sampling.
   *
   * Consumes 32-bit blocks from the hash stream, rehashing when exhausted.
   * Rejects values that would cause modulo bias for the given range.
   * Shared by both Mines and Blackjack Fisher-Yates implementations.
   *
   * @param serverSeed    The server seed for potential rehashing.
   * @param currentHashHex The current hash (mutated on exhaustion).
   * @param chunkCounter   Tracks consumption position (mutated on read).
   * @param range          The exclusive upper bound for the result [0, range).
   * @return int An unbiased random index within [0, range).
   */
  static int selectUnbiasedIndex(const std::string &serverSeed,
                                 std::string &currentHashHex, int &chunkCounter,
                                 int range);

  /**
   * @brief Validates common seed and nonce parameters.
   *
   * @param serverSeed Must be non-empty.
   * @param clientSeed Must be non-empty.
   * @param nonce      Must be positive (> 0).
   * @throws std::invalid_argument If any parameter is invalid.
   */
  static void validateSeeds(const std::string &serverSeed,
                            const std::string &clientSeed, long nonce);
};
